vlog -work work D:/JiZuKeShe/Lab3/simulation/modelsim/ALU_Test.vwf.vt
vsim -novopt -c -t 1ps -L cycloneive_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.16_Bit_ALU_vlg_vec_tst
onerror {resume}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[15]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[14]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[13]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[12]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[11]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[10]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[9]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[8]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[7]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[6]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[5]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[4]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[3]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[2]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[1]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/A[0]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[15]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[14]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[13]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[12]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[11]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[10]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[9]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[8]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[7]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[6]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[5]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[4]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[3]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[2]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[1]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/B[0]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/C}
add wave {16_Bit_ALU_vlg_vec_tst/i1/C0}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[15]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[14]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[13]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[12]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[11]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[10]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[9]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[8]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[7]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[6]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[5]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[4]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[3]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[2]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[1]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/F[0]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/M}
add wave {16_Bit_ALU_vlg_vec_tst/i1/S}
add wave {16_Bit_ALU_vlg_vec_tst/i1/S[3]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/S[2]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/S[1]}
add wave {16_Bit_ALU_vlg_vec_tst/i1/S[0]}
run -all
