vlog -work work D:/JiZuKeShe/Lab3/simulation/modelsim/TotalTest.vwf.vt
vsim -novopt -c -t 1ps -L cycloneive_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.Lab3_vlg_vec_tst
onerror {resume}
add wave {Lab3_vlg_vec_tst/i1/X}
add wave {Lab3_vlg_vec_tst/i1/X[15]}
add wave {Lab3_vlg_vec_tst/i1/X[14]}
add wave {Lab3_vlg_vec_tst/i1/X[13]}
add wave {Lab3_vlg_vec_tst/i1/X[12]}
add wave {Lab3_vlg_vec_tst/i1/X[11]}
add wave {Lab3_vlg_vec_tst/i1/X[10]}
add wave {Lab3_vlg_vec_tst/i1/X[9]}
add wave {Lab3_vlg_vec_tst/i1/X[8]}
add wave {Lab3_vlg_vec_tst/i1/X[7]}
add wave {Lab3_vlg_vec_tst/i1/X[6]}
add wave {Lab3_vlg_vec_tst/i1/X[5]}
add wave {Lab3_vlg_vec_tst/i1/X[4]}
add wave {Lab3_vlg_vec_tst/i1/X[3]}
add wave {Lab3_vlg_vec_tst/i1/X[2]}
add wave {Lab3_vlg_vec_tst/i1/X[1]}
add wave {Lab3_vlg_vec_tst/i1/X[0]}
add wave {Lab3_vlg_vec_tst/i1/Y}
add wave {Lab3_vlg_vec_tst/i1/Y[15]}
add wave {Lab3_vlg_vec_tst/i1/Y[14]}
add wave {Lab3_vlg_vec_tst/i1/Y[13]}
add wave {Lab3_vlg_vec_tst/i1/Y[12]}
add wave {Lab3_vlg_vec_tst/i1/Y[11]}
add wave {Lab3_vlg_vec_tst/i1/Y[10]}
add wave {Lab3_vlg_vec_tst/i1/Y[9]}
add wave {Lab3_vlg_vec_tst/i1/Y[8]}
add wave {Lab3_vlg_vec_tst/i1/Y[7]}
add wave {Lab3_vlg_vec_tst/i1/Y[6]}
add wave {Lab3_vlg_vec_tst/i1/Y[5]}
add wave {Lab3_vlg_vec_tst/i1/Y[4]}
add wave {Lab3_vlg_vec_tst/i1/Y[3]}
add wave {Lab3_vlg_vec_tst/i1/Y[2]}
add wave {Lab3_vlg_vec_tst/i1/Y[1]}
add wave {Lab3_vlg_vec_tst/i1/Y[0]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[15]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[14]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[13]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[12]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[11]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[10]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[9]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[8]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[7]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[6]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[5]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[4]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[3]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[2]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[1]}
add wave {Lab3_vlg_vec_tst/i1/ALU_OUT[0]}
add wave {Lab3_vlg_vec_tst/i1/CLK}
add wave {Lab3_vlg_vec_tst/i1/CLK1}
add wave {Lab3_vlg_vec_tst/i1/CLK2}
add wave {Lab3_vlg_vec_tst/i1/CLK3}
add wave {Lab3_vlg_vec_tst/i1/CLK4}
add wave {Lab3_vlg_vec_tst/i1/M}
add wave {Lab3_vlg_vec_tst/i1/S}
add wave {Lab3_vlg_vec_tst/i1/S[3]}
add wave {Lab3_vlg_vec_tst/i1/S[2]}
add wave {Lab3_vlg_vec_tst/i1/S[1]}
add wave {Lab3_vlg_vec_tst/i1/S[0]}
add wave {Lab3_vlg_vec_tst/i1/C0}
run -all
