vlog -work work D:/JiZuKeShe/Lab3/simulation/modelsim/MUL_Test.vwf.vt
vsim -novopt -c -t 1ps -L cycloneive_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.16_Bit_MUL_vlg_vec_tst
onerror {resume}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[15]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[14]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[13]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[12]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[11]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[10]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[9]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[8]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[7]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[6]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[5]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[4]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[3]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[2]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[1]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/A[0]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[15]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[14]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[13]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[12]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[11]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[10]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[9]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[8]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[7]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[6]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[5]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[4]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[3]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[2]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[1]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/ACC[0]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[15]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[14]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[13]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[12]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[11]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[10]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[9]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[8]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[7]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[6]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[5]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[4]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[3]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[2]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[1]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/B[0]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/CLK}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[15]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[14]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[13]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[12]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[11]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[10]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[9]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[8]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[7]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[6]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[5]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[4]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[3]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[2]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[1]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/MQ[0]}
add wave {16_Bit_MUL_vlg_vec_tst/i1/START}
add wave {16_Bit_MUL_vlg_vec_tst/i1/RST}
run -all
